### PR TITLE
switch to mermaid 8.4.0

### PR DESCRIPTION
**Pull request by rflament-icabbi**

### CODE REVIEW

**Comment by ldz-w** [comment]
Anybody home? Or is this project abandoned?

**Comment by jakiestfu** [comment]
Meeerrrrgggeee!

**Comment by NansPellicari** [comment]
Hi guys, development repo as been moved here https://github.com/mermaid-js/mermaid.cli/

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

**Pull request closed without merging**
