### PR TITLE
Allow changing DPI of generated image

### LINKED ISSUE #51: Is there any way to set dpi for png
in some condition , I have to use png instead of svg
but the default dpi for png is too low (=72)
Is there any way to set dpi for png

### PR DESCRIPTION
**Pull request by Fenntasy**
This PR would allow setting the DPI of a screenshot to have a better quality image in the end.

A DPI of 2 is equivalent to 4 times the size of the image and is roughly what happens in a retina screen.

This would also fix #51

### CODE REVIEW

**Comment by agusmba** [comment]
My 2c, personally I wouldn't use the new option name "dpi" since it has a different meaning from what you're using it for.
Maybe "scale" as an alternative name?
@tylerlong can probably suggest a better one.

**Comment by Fenntasy** [comment]
You're right, I made the change :)

**Comment by enbandari** [comment]
Any news about this?

**Comment by LouisMaycol** [comment]
Hoping this could be merged already. Tried and applied the fix on my local copy and works as intended.

**Comment by zachwill** [comment]
👍 This would be really useful when creating Mermaid files locally on my Mac. /cc @tylerlong

**Comment by d0c-s4vage** [comment]
Any progress on this? I'm adding mermaid-js support to [lookatme](https://github.com/d0c-s4vage/lookatme). I'm willing to help resolve any blockers to get this in.

**Comment by IAXES** [comment]
+FYI: https://github.com/mermaidjs/mermaid.cli/issues/3

This functionality is present and can be used.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo.

It looks like somebody has already made quite a similar contribution a few years ago too:
https://github.com/mermaid-js/mermaid-cli/commit/6d7cbcb56b501e9c0a84616a33b2ffc21db25361, so this feature already exists in the `@mermaid-js/mermaid-cli` package.

The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

**Pull request closed without merging**
