### PR TITLE
Scaling <svg> root to fit browser window - fix #3

### LINKED ISSUE #3: width / height options do not alter the size of the generated PNG
Hi.

I'm not sure if this is a bug or feature request,
but currently it is not posible to generate a bigger PNG using the `-w` / `-H` flags

### PR DESCRIPTION
**Pull request by Lucas-C**
I did not a commander flag because I think it is always preferable to have a transparent background
What do you think ?

### CODE REVIEW

**Comment by tylerlong** [comment]
Sorry for the delay. But I need to do some manual test before I can merge it.

**Comment by Lucas-C** [comment]
No problem :)

**Comment by tylerlong** [comment]
Finally I have some time to test it.

It works for PNG files. 

But it has no effect for svg (I know svg is scalable but it's ideal to change the default size.)

It behaves strangely for pdf files.

Another concern is by default mermaid will choose a "proper" size if the page is too wide.  This PR will break it, so user has to specify a proper width manually every time.

**Comment by tylerlong** [comment]
Overall this should be a mermaid issue. Mermaid doesn't allow user to manually set a width for the charts. It figures out the width according to page width and it also doesn't always take 100% of the page width.

Feel free to create an issue for the mermaid project. I will close this PR now.

**Pull request closed without merging**
