### PR TITLE
deps: upgrade mermaid to 8.2.3

### PR DESCRIPTION
**Pull request by fengmk2**

### CODE REVIEW

**Comment by caillou** [comment]
Is there a particular reason, that this does not get merged?

**Comment by jbenet** [comment]
probably maintainer needs help -- mermaid is a great project, and needs more support/help

**Comment by caillou** [comment]
@jbenet thanks for your idea. This being said, how can we better help than with making PRs? This is a genuine question, my understanding was that PRs are the best way to help…

**Comment by oscarvarto** [comment]
Better yet: could we have an update straight to 8.4.0, to enjoy State Diagrams support?

**Pull request closed without merging**
