### PR TITLE
Generating PNG images with a transparent background

### PR DESCRIPTION
**Pull request by Lucas-C**

### CODE REVIEW

**Comment by tylerlong** [comment]
Could you please make it a CLI option instead?  So user can turn it on/off via command line.

**Comment by Lucas-C** [comment]
Yeah, I thought about this, but then realized I couldn't find any example where one would prefer a white background over a transparent one.

So, I'm OK to add a flag, but do you really think it's necessary ?

**Comment by tylerlong** [comment]
I think it's really cool if we could let user choose background colors, such as transparent, white, red, black, #F0F0F0....etc.  I will do it whenever I have more free time. :)

**Comment by Lucas-C** [comment]
Ok :)

**Comment by tylerlong** [comment]
Done: https://github.com/mermaidjs/mermaid.cli/commit/010ee302a641bfda1e364ed08c33f9ede139cdef

**Comment by tylerlong** [comment]
I use white color as default because white is the default color for any web page. It's also the default color for puppeteer.  If you want transparent color just `-b transparent`.

**Comment by Lucas-C** [comment]
Thanks

**Pull request closed without merging**
